name: receipt_example
description: A printing receipt of invoices.

publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar_flutter_libs: ^2.2.1
  isar: ^2.2.1
  path_provider: ^2.0.9
  equatable: ^2.0.3
  uuid: ^3.0.5
  http: ^0.13.4
  printing: ^5.3.0
  open_file: ^3.2.1
  url_launcher: ^6.0.6
  intl: ^0.17.0
  gap: ^2.0.0
  receipt:
  # receipt:
  #   path: ".."

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
#  flutter packages pub run build_runner build --delete-conflicting-outputs

