name: receipt
description: A new receipt package for print
version: 1.0.0-dev.2
repository: "https://github.com/yegobox/receipt"

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.7.5
  pdf: ^3.7.3
  open_file: ^3.2.1
  gap: ^2.0.0
  flipper_models: ^0.0.1-dev.5
  isar: ^2.2.0+1
  isar_flutter_libs: ^2.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  isar_generator: 2.2.0+1

flutter:
